package com.hadjshell.mahjong.domain.model;

public enum SettlementReason {
  SELF_DRAW_DOUBLE,
  DISCARDER_DOUBLE,
  DEALER_DOUBLE,
  CLOSED_HAND_DOUBLE,
  THREE_CLOSED_LOSERS_DOUBLE,
  KONG_REPLACEMENT_WIN_DOUBLE,
  SEVEN_PAIRS_FIXED,
  ALL_TRIPLETS_FIXED,
  EXHAUSTIVE_DRAW,
  DIRECT_EXPOSED_KONG,
  UPGRADED_KONG,
  CONCEALED_KONG,
  DRAGON_KONG
}
